# Generated by Django 5.2.9 on 2025-12-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_is_verified_teacher_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reset_token_created',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='verification_token',
        ),
    ]
