# Generated by Django 5.2.9 on 2025-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_teacher_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
